# Generated by Django 4.2 on 2024-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_day_of_week_workinghour_end_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='end_time',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_time',
            field=models.CharField(max_length=256),
        ),
    ]
