# Generated by Django 4.2 on 2024-04-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactus_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='تیتر صفحه اصلی')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='بنر صفحه اصلی')),
                ('bottom_text', models.TextField(verbose_name='متن پایین صفحه')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'اطلاعات تماس', 'verbose_name_plural': 'اطلاعات تماس'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('created_date',), 'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'خبرنامه', 'verbose_name_plural': 'خبرنامه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='workinghour',
            options={'verbose_name': 'ساعات کاری', 'verbose_name_plural': 'ساعات کاری'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='landline_phone',
            field=models.CharField(max_length=15, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone',
            field=models.CharField(max_length=15, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='workingHour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.workinghour', verbose_name='ساعت کاری'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='end_day',
            field=models.CharField(choices=[('Sat', 'شنبه'), ('Sun', 'یکشنبه'), ('Mon', 'دوشنبه'), ('Tue', 'سه شنبه'), ('Wed', 'چهار شنبه'), ('Thu', 'پنج شنبه'), ('Fri', 'جمعه')], max_length=3, verbose_name='روز پایان'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='end_time',
            field=models.CharField(max_length=256, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_day',
            field=models.CharField(choices=[('Sat', 'شنبه'), ('Sun', 'یکشنبه'), ('Mon', 'دوشنبه'), ('Tue', 'سه شنبه'), ('Wed', 'چهار شنبه'), ('Thu', 'پنج شنبه'), ('Fri', 'جمعه')], max_length=3, verbose_name='روز شروع'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_time',
            field=models.CharField(max_length=256, verbose_name='زمان شروع'),
        ),
    ]
