# Generated by Django 4.2 on 2024-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_homepage_options_homepage_top_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=models.TextField(default=1, verbose_name=' متن درباره صفحه اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='aboutـbanner',
            field=models.ImageField(default=1, upload_to='banners/', verbose_name=' بنر در باره ما صفحه اصلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='aboutـtitle',
            field=models.CharField(default=1, max_length=255, verbose_name='تیتر  درباره ما صفحه اصلی'),
            preserve_default=False,
        ),
    ]
