# Generated by Django 4.2 on 2024-04-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_homepage_about_text_homepage_aboutـbanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('aboutuspage_image', models.ImageField(blank=True, null=True, upload_to='aboutus/', verbose_name='تصویر صفحه درباره ما ')),
                ('content', models.TextField(verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'صفحه تماس با ما',
            },
        ),
    ]
