# Generated by Django 4.2 on 2024-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'صفحه درباره ما'},
        ),
    ]
