# Generated by Django 4.2 on 2024-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contact_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='whatsapp '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='instagram ID'),
        ),
    ]
